// shopData.js - Heer Ranjha product catalogue

export const PRODUCTS = [
  // ── MEN ──────────────────────────────────────────
  {
    id: "HKM-304",
    name: "Pink Matka Kurta Set",
    category: "Men",
    subCategory: "Kurta Sets",
    collection: "Nayi Leher",
    fabric: "Matka Silk",
    detail: "Cotton Pant · Hand Embroidery",
    price: 8500,
    badge: "New",
    colorA: "#D4A090",
    colorB: "#8A5040",
    cx: 55, cy: 40,
  },
  {
    id: "HKM-318",
    name: "Ivory Dupion Kurta Set",
    category: "Men",
    subCategory: "Kurta Sets",
    collection: "Asaya",
    fabric: "Dupion",
    detail: "Cotton Pant · Hand Embroidery",
    price: 9200,
    badge: null,
    colorA: "#E0D4B8",
    colorB: "#A09060",
    cx: 45, cy: 38,
  },
  {
    id: "HKM-325",
    name: "Royal Blue Kurta Set",
    category: "Men",
    subCategory: "Kurta Sets",
    collection: "Roomani",
    fabric: "Dupion",
    detail: "Cotton Pant · Machine Embroidery",
    price: 7800,
    badge: null,
    colorA: "#6080B8",
    colorB: "#283870",
    cx: 60, cy: 42,
  },
  {
    id: "HKM-338",
    name: "Rust Matka Kurta Set",
    category: "Men",
    subCategory: "Kurta Sets",
    collection: "Ganga Jamuni",
    fabric: "Matka Silk",
    detail: "Cotton Pant · Hand Embroidery",
    price: 8000,
    badge: null,
    colorA: "#C07050",
    colorB: "#783820",
    cx: 50, cy: 45,
  },
  {
    id: "HJM-311",
    name: "Sky Blue Nehru Jacket",
    category: "Men",
    subCategory: "Nehru Jackets",
    collection: "Nayi Leher",
    fabric: "Dupion",
    detail: "Hand Embroidery · Indian Ethnic",
    price: 6500,
    badge: "New",
    colorA: "#80B8C8",
    colorB: "#305070",
    cx: 62, cy: 38,
  },
  {
    id: "HJM-322",
    name: "Maroon Nehru Jacket",
    category: "Men",
    subCategory: "Nehru Jackets",
    collection: "Roomani",
    fabric: "Dupion",
    detail: "Hand Embroidery · Indian Ethnic",
    price: 6800,
    badge: null,
    colorA: "#904050",
    colorB: "#501828",
    cx: 40, cy: 42,
  },
  {
    id: "HJM-334",
    name: "Olive Raw Silk Nehru Jacket",
    category: "Men",
    subCategory: "Nehru Jackets",
    collection: "Ganga Jamuni",
    fabric: "Raw Silk",
    detail: "Hand Embroidery · Indian Ethnic",
    price: 7200,
    badge: null,
    colorA: "#788858",
    colorB: "#384820",
    cx: 55, cy: 40,
  },
  {
    id: "HSD-348",
    name: "Mint Green Sherwani Set",
    category: "Men",
    subCategory: "Sherwanis",
    collection: "Nayi Leher",
    fabric: "Dupion",
    detail: "Hand Embroidery · Indian Ethnic",
    price: 22000,
    badge: null,
    colorA: "#80C0A8",
    colorB: "#308060",
    cx: 58, cy: 36,
  },
  {
    id: "HSD-360",
    name: "Ivory Raw Silk Sherwani Set",
    category: "Men",
    subCategory: "Sherwanis",
    collection: "Asaya",
    fabric: "Raw Silk",
    detail: "Hand Embroidery · Indo-Western",
    price: 25000,
    badge: null,
    colorA: "#E8E0CC",
    colorB: "#C0B080",
    cx: 48, cy: 44,
  },
  {
    id: "HBM-336",
    name: "Navy Blue Bandhgala Set",
    category: "Men",
    subCategory: "Bandhgalas",
    collection: "Nayi Leher",
    fabric: "Matka Silk",
    detail: "Hand Embroidery · Indian Ethnic",
    price: 18000,
    badge: null,
    colorA: "#304878",
    colorB: "#101838",
    cx: 52, cy: 40,
  },
  {
    id: "HBM-344",
    name: "Sage Green Bandhgala Set",
    category: "Men",
    subCategory: "Bandhgalas",
    collection: "Asaya",
    fabric: "Dupion",
    detail: "Hand Embroidery · Indo-Western",
    price: 19500,
    badge: null,
    colorA: "#789878",
    colorB: "#385838",
    cx: 60, cy: 38,
  },
  {
    id: "HBM-358",
    name: "Champagne Bandhgala Set",
    category: "Men",
    subCategory: "Bandhgalas",
    collection: "Ganga Jamuni",
    fabric: "Raw Silk",
    detail: "Machine Embroidery · Indo-Western",
    price: 17000,
    badge: null,
    colorA: "#C8B880",
    colorB: "#907840",
    cx: 45, cy: 42,
  },
  // ── WOMEN ────────────────────────────────────────
  {
    id: "AL-1430",
    name: "Red Chanderi Lehenga",
    category: "Women",
    subCategory: "Lehengas",
    collection: "Asaya",
    fabric: "Chanderi",
    detail: "Organza Dupatta · Hand Embroidery",
    price: 35000,
    badge: "New",
    colorA: "#C03040",
    colorB: "#801020",
    cx: 55, cy: 40,
  },
  {
    id: "AL-1445",
    name: "Pink Organza Lehenga",
    category: "Women",
    subCategory: "Lehengas",
    collection: "Nayi Leher",
    fabric: "Organza",
    detail: "3PC Set · Hand Embroidery",
    price: 32000,
    badge: null,
    colorA: "#D890A0",
    colorB: "#905060",
    cx: 50, cy: 36,
  },
  {
    id: "AL-1458",
    name: "Gold Tissue Lehenga",
    category: "Women",
    subCategory: "Lehengas",
    collection: "Roomani",
    fabric: "Tissue",
    detail: "3PC Set · Machine Embroidery",
    price: 45000,
    badge: null,
    colorA: "#C8A040",
    colorB: "#806010",
    cx: 62, cy: 42,
  },
  {
    id: "AL-1462",
    name: "Ivory Organza Lehenga",
    category: "Women",
    subCategory: "Lehengas",
    collection: "Asaya",
    fabric: "Organza",
    detail: "3PC Set · Hand Embroidery",
    price: 38000,
    badge: "Sold Out",
    colorA: "#F0E8D0",
    colorB: "#C8B898",
    cx: 48, cy: 44,
  },
  {
    id: "AI-1426",
    name: "Midnight Blue Dupion Co-ord Set",
    category: "Women",
    subCategory: "Co-ord Sets",
    collection: "Asaya",
    fabric: "Dupion",
    detail: "2PC Set · Hand Embroidery",
    price: 18000,
    badge: null,
    colorA: "#283868",
    colorB: "#081028",
    cx: 55, cy: 38,
  },
  {
    id: "AI-1434",
    name: "Teal Chanderi Co-ord Set",
    category: "Women",
    subCategory: "Co-ord Sets",
    collection: "Nayi Leher",
    fabric: "Chanderi",
    detail: "2PC Set · Hand Embroidery",
    price: 16500,
    badge: null,
    colorA: "#509898",
    colorB: "#205858",
    cx: 60, cy: 40,
  },
  {
    id: "AI-1448",
    name: "Sage Dupion Co-ord Set",
    category: "Women",
    subCategory: "Co-ord Sets",
    collection: "Ganga Jamuni",
    fabric: "Dupion",
    detail: "2PC Set · Machine Embroidery",
    price: 15000,
    badge: null,
    colorA: "#788858",
    colorB: "#405030",
    cx: 45, cy: 42,
  },
  {
    id: "AS-2077",
    name: "Green Dupion Suit Set",
    category: "Women",
    subCategory: "Suit Sets",
    collection: "Nayi Leher",
    fabric: "Dupion",
    detail: "Red Organza Dupatta · Indian Ethnic",
    price: 12000,
    badge: null,
    colorA: "#508048",
    colorB: "#204820",
    cx: 52, cy: 38,
  },
  {
    id: "AS-2088",
    name: "Beige Chanderi Suit Set",
    category: "Women",
    subCategory: "Suit Sets",
    collection: "Asaya",
    fabric: "Chanderi",
    detail: "Organza Dupatta · Hand Embroidery",
    price: 11500,
    badge: null,
    colorA: "#C8B898",
    colorB: "#907848",
    cx: 58, cy: 44,
  },
  {
    id: "AS-2094",
    name: "Lavender Chanderi Suit Set",
    category: "Women",
    subCategory: "Suit Sets",
    collection: "Roomani",
    fabric: "Chanderi",
    detail: "Organza Dupatta · Hand Embroidery",
    price: 10800,
    badge: null,
    colorA: "#9088B8",
    colorB: "#504878",
    cx: 50, cy: 40,
  },
  {
    id: "AS-1756",
    name: "Silver Tissue Sharara Set",
    category: "Women",
    subCategory: "Suit Sets",
    collection: "Asaya",
    fabric: "Tissue",
    detail: "4PC Set with Potli · Hand Embroidery",
    price: 28000,
    badge: null,
    colorA: "#C0B8C8",
    colorB: "#808090",
    cx: 55, cy: 38,
  },
  {
    id: "AS-1768",
    name: "Peach Dupion Saree",
    category: "Women",
    subCategory: "Sarees",
    collection: "Ganga Jamuni",
    fabric: "Dupion",
    detail: "Hand Embroidery · Indian Ethnic",
    price: 15500,
    badge: null,
    colorA: "#D8A880",
    colorB: "#A07040",
    cx: 48, cy: 42,
  },
];

export const CATEGORIES = [
  { label: "All", value: "All" },
  { label: "Men", value: "Men" },
  { label: "Women", value: "Women" },
];

export const SUB_CATEGORIES = [
  "Kurta Sets",
  "Nehru Jackets",
  "Sherwanis",
  "Bandhgalas",
  "Lehengas",
  "Co-ord Sets",
  "Suit Sets",
  "Sarees",
];

export const COLLECTIONS = [
  "Nayi Leher",
  "Asaya",
  "Roomani",
  "Ganga Jamuni",
];

export const FABRICS = [
  "Matka Silk",
  "Dupion",
  "Chanderi",
  "Raw Silk",
  "Organza",
  "Tissue",
];

export const SORT_OPTIONS = [
  { label: "Newest First", value: "newest" },
  { label: "Price: Low to High", value: "price_asc" },
  { label: "Price: High to Low", value: "price_desc" },
  { label: "Name: A to Z", value: "name_asc" },
];

export const PER_PAGE = 12;

export function formatPrice(n) {
  return "\u20B9" + n.toLocaleString("en-IN");
}
